name: Flutter Test

on:
  pull_request:
    branches:
      - main  # main 브랜치로 PR 생성 시 실행

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Flutter 설치
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  

      # 2. 의존성 설치
      - name: Install dependencies
        run: flutter pub get

      # 3. 테스트 실행
      - name: Run tests
        run: flutter test
